[package]
name = "dispatcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
types.workspace = true
store.workspace = true
auth.workspace = true
vcs.workspace = true
container.workspace = true
agent.workspace = true
chrono.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
test-utils.workspace = true
