//! SSH CA (spec §7.3–7.4) and ref authorization (spec §5.2).
//!
//! Cert signing shells out to `ssh-keygen` — the CA key was generated by it
//! (§12.1) and the deploy host runs sshd anyway. Authorization context rides
//! in the certificate's forced command (`chuggernaut ssh-shell ...`), which
//! stock sshd enforces via `TrustedUserCAKeys`; the shell helper and each
//! repo's pre-receive hook call back into the pure functions below.

use crate::AuthError;
use std::collections::HashMap;
use std::path::PathBuf;
use types::ProjectRole;

/// Login principal present in every cert: sshd only accepts certificates
/// whose principals include the target account, so all git traffic logs in
/// as the `git` user (its `AuthorizedPrincipalsFile` lists exactly this).
/// The semantic principal (§5.2) travels alongside it and in the cert's
/// forced command.
pub const SSH_LOGIN_PRINCIPAL: &str = "git";

/// Env names `ssh-shell` exports for the repo's pre-receive hook.
pub const ENV_PRINCIPAL: &str = "CHUGGERNAUT_PRINCIPAL";
pub const ENV_ACCESS: &str = "CHUGGERNAUT_ACCESS";
pub const ENV_ROLES: &str = "CHUGGERNAUT_ROLES";
pub const ENV_REPO: &str = "CHUGGERNAUT_REPO";

/// Hook body written into `hooks/pre-receive` at project creation (§12.2).
/// Bakes the path the binary has *on the SSH host*. The no-identity fast
/// path (local/`file://` access — the dispatcher's own pushes) lives in the
/// script itself so it holds even where the baked path doesn't exist (repos
/// shared between the host dispatcher and an sshd container).
pub fn pre_receive_hook_body(chuggernaut_bin: &std::path::Path) -> String {
    format!(
        "#!/bin/sh\n[ -z \"${ENV_PRINCIPAL}\" ] && exit 0\nexec {} ssh-authz\n",
        chuggernaut_bin.display()
    )
}

/// Whether a per-job certificate may push (§7.4: work rw, eval ro).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CertAccess {
    ReadWrite,
    ReadOnly,
}

impl CertAccess {
    pub fn as_str(&self) -> &'static str {
        match self {
            CertAccess::ReadWrite => "rw",
            CertAccess::ReadOnly => "ro",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "rw" => Some(CertAccess::ReadWrite),
            "ro" => Some(CertAccess::ReadOnly),
            _ => None,
        }
    }
}

/// Parsed SSH principal (§5.2 table rows).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Principal {
    /// `job:{owner}/{project}:{seq}`
    Job { owner: String, project: String, seq: u64 },
    /// `dispatcher`
    Dispatcher,
    /// Anything else: a user email.
    User { email: String },
}

impl Principal {
    pub fn parse(s: &str) -> Self {
        if s == "dispatcher" {
            return Principal::Dispatcher;
        }
        if let Some(rest) = s.strip_prefix("job:")
            && let Some((slug, seq)) = rest.rsplit_once(':')
            && let Some((owner, project)) = slug.split_once('/')
            && let Ok(seq) = seq.parse()
        {
            return Principal::Job {
                owner: owner.to_string(),
                project: project.to_string(),
                seq,
            };
        }
        Principal::User { email: s.to_string() }
    }
}

/// §5.2 pull column. `roles` is the user's `project_roles` claim (from the
/// cert's forced command); job and dispatcher principals need none.
pub fn authorize_pull(
    principal: &Principal,
    roles: &HashMap<String, ProjectRole>,
    owner: &str,
    project: &str,
) -> bool {
    match principal {
        Principal::Dispatcher => true,
        Principal::Job { owner: o, project: p, .. } => o == owner && p == project,
        Principal::User { .. } => {
            roles.get(&format!("{owner}/{project}")) >= Some(&ProjectRole::Viewer)
        }
    }
}

/// §5.2 push column, evaluated per updated ref (pre-receive hook). Protected
/// refs (the default branch, tags) are dispatcher-only.
pub fn authorize_ref_push(
    principal: &Principal,
    access: CertAccess,
    roles: &HashMap<String, ProjectRole>,
    owner: &str,
    project: &str,
    refname: &str,
    default_branch: &str,
) -> bool {
    if access == CertAccess::ReadOnly {
        return false;
    }
    match principal {
        Principal::Dispatcher => true,
        Principal::Job { owner: o, project: p, seq } => {
            o == owner && p == project && refname == format!("refs/heads/job/{seq}")
        }
        Principal::User { .. } => {
            roles.get(&format!("{owner}/{project}")) >= Some(&ProjectRole::Member)
                && is_job_branch(refname)
                && refname != format!("refs/heads/{default_branch}")
        }
    }
}

/// Entry gate for `git-receive-pack` (before any ref is known): may this
/// principal push *anything* to the repo? Per-ref enforcement happens in the
/// pre-receive hook via [`authorize_ref_push`].
pub fn authorize_push_entry(
    principal: &Principal,
    access: CertAccess,
    roles: &HashMap<String, ProjectRole>,
    owner: &str,
    project: &str,
) -> bool {
    if access == CertAccess::ReadOnly {
        return false;
    }
    match principal {
        Principal::Dispatcher => true,
        Principal::Job { owner: o, project: p, .. } => o == owner && p == project,
        Principal::User { .. } => {
            roles.get(&format!("{owner}/{project}")) >= Some(&ProjectRole::Member)
        }
    }
}

fn is_job_branch(refname: &str) -> bool {
    refname
        .strip_prefix("refs/heads/job/")
        .is_some_and(|seq| !seq.is_empty() && seq.chars().all(|c| c.is_ascii_digit()))
}

/// The two git services reachable over SSH.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GitService {
    UploadPack,  // pull / clone
    ReceivePack, // push
}

impl GitService {
    pub fn command(&self) -> &'static str {
        match self {
            GitService::UploadPack => "git-upload-pack",
            GitService::ReceivePack => "git-receive-pack",
        }
    }
}

/// Parse `SSH_ORIGINAL_COMMAND` (`git-upload-pack '/acme/api.git'`, also the
/// `git upload-pack` spelling) into service + owner + project. Anything else
/// — including path traversal and option-looking paths — is None (deny).
pub fn parse_git_command(original: &str) -> Option<(GitService, String, String)> {
    let rest = original.trim();
    let (service, path) = if let Some(p) = strip_service(rest, "upload-pack") {
        (GitService::UploadPack, p)
    } else if let Some(p) = strip_service(rest, "receive-pack") {
        (GitService::ReceivePack, p)
    } else {
        return None;
    };
    let path = path.trim().trim_matches('\'').trim_matches('"');
    let path = path.strip_prefix('/').unwrap_or(path);
    let path = path.strip_suffix(".git").unwrap_or(path);
    let (owner, project) = path.split_once('/')?;
    let valid = |s: &str| {
        !s.is_empty()
            && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    };
    (valid(owner) && valid(project))
        .then(|| (service, owner.to_string(), project.to_string()))
}

fn strip_service<'a>(command: &'a str, service: &str) -> Option<&'a str> {
    command
        .strip_prefix(&format!("git-{service} "))
        .or_else(|| command.strip_prefix(&format!("git {service} ")))
}

/// A freshly issued per-job SSH credential (§7.4): ephemeral private key +
/// CA-signed certificate, both in OpenSSH text form, ready for injection.
pub struct JobSshCredential {
    pub private_key: String,
    pub public_key: String,
    pub certificate: String,
}

/// Signs certificates with the platform CA key (`ssh_ca`, §12.1).
pub struct SshCa {
    ca_key_path: PathBuf,
}

impl SshCa {
    pub fn new(ca_key_path: impl Into<PathBuf>) -> Self {
        Self { ca_key_path: ca_key_path.into() }
    }

    /// §7.3: sign a user-submitted public key. Principal = email, 24h
    /// validity; `project_roles` ride in the forced command for the
    /// authorization hooks.
    pub async fn sign_user_cert(
        &self,
        public_key_openssh: &str,
        email: &str,
        roles: &HashMap<String, ProjectRole>,
        validity: chrono::Duration,
    ) -> Result<String, AuthError> {
        use base64::Engine;
        let roles_json = serde_json::to_string(roles)
            .map_err(|e| AuthError::Internal(e.to_string()))?;
        let roles_b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(roles_json);
        let force_command =
            format!("chuggernaut ssh-shell --kind user --principal {email} --roles {roles_b64}");
        self.sign(public_key_openssh, &format!("user:{email}"), email, validity, &force_command)
            .await
    }

    /// §7.4: mint an ephemeral keypair and sign it for a job container.
    pub async fn issue_job_credential(
        &self,
        owner: &str,
        project: &str,
        seq: u64,
        access: CertAccess,
        validity: chrono::Duration,
    ) -> Result<JobSshCredential, AuthError> {
        let dir = tempfile::tempdir().map_err(internal)?;
        let key_path = dir.path().join("id_ed25519");
        run("ssh-keygen", &[
            "-t", "ed25519", "-N", "", "-q",
            "-C", &format!("job-{owner}-{project}-{seq}"),
            "-f", path_str(&key_path)?,
        ])
        .await?;
        let public_key = tokio::fs::read_to_string(key_path.with_extension("pub"))
            .await
            .map_err(internal)?;

        let principal = crate::job_ssh_principal(owner, project, seq);
        let force_command = format!(
            "chuggernaut ssh-shell --kind job --principal {principal} --access {}",
            access.as_str()
        );
        let certificate = self
            .sign(&public_key, &principal, &principal, validity, &force_command)
            .await?;
        let private_key = tokio::fs::read_to_string(&key_path).await.map_err(internal)?;
        Ok(JobSshCredential { private_key, public_key, certificate })
    }

    async fn sign(
        &self,
        public_key_openssh: &str,
        key_id: &str,
        principal: &str,
        validity: chrono::Duration,
        force_command: &str,
    ) -> Result<String, AuthError> {
        let dir = tempfile::tempdir().map_err(internal)?;
        let pub_path = dir.path().join("subject.pub");
        tokio::fs::write(&pub_path, public_key_openssh.trim().to_string() + "\n")
            .await
            .map_err(internal)?;
        run("ssh-keygen", &[
            "-q",
            "-s", path_str(&self.ca_key_path)?,
            "-I", key_id,
            "-n", &format!("{principal},{SSH_LOGIN_PRINCIPAL}"),
            "-V", &format!("+{}s", validity.num_seconds().max(1)),
            "-O", "clear",
            "-O", &format!("force-command={force_command}"),
            path_str(&pub_path)?,
        ])
        .await?;
        tokio::fs::read_to_string(dir.path().join("subject-cert.pub"))
            .await
            .map_err(internal)
    }
}

fn path_str(path: &std::path::Path) -> Result<&str, AuthError> {
    path.to_str()
        .ok_or_else(|| AuthError::Internal(format!("non-utf8 path {}", path.display())))
}

fn internal(e: impl std::fmt::Display) -> AuthError {
    AuthError::Internal(e.to_string())
}

async fn run(program: &str, args: &[&str]) -> Result<(), AuthError> {
    let out = tokio::process::Command::new(program)
        .args(args)
        .output()
        .await
        .map_err(|e| AuthError::Internal(format!("running {program}: {e}")))?;
    if !out.status.success() {
        return Err(AuthError::Internal(format!(
            "{program} {args:?} failed: {}",
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roles(role: ProjectRole) -> HashMap<String, ProjectRole> {
        HashMap::from([("acme/api".to_string(), role)])
    }

    #[test]
    fn principal_parsing() {
        assert_eq!(
            Principal::parse("job:acme/api:42"),
            Principal::Job { owner: "acme".into(), project: "api".into(), seq: 42 }
        );
        assert_eq!(Principal::parse("dispatcher"), Principal::Dispatcher);
        assert_eq!(
            Principal::parse("david@example.com"),
            Principal::User { email: "david@example.com".into() }
        );
        // Malformed job principals fall through to user (deny-by-role).
        assert!(matches!(Principal::parse("job:acme:nope"), Principal::User { .. }));
    }

    #[test]
    fn git_command_parsing() {
        let ok = |cmd: &str| parse_git_command(cmd).unwrap();
        assert_eq!(
            ok("git-upload-pack '/acme/api.git'"),
            (GitService::UploadPack, "acme".into(), "api".into())
        );
        assert_eq!(
            ok("git-receive-pack '/acme/api.git'"),
            (GitService::ReceivePack, "acme".into(), "api".into())
        );
        assert_eq!(
            ok("git upload-pack acme/api"),
            (GitService::UploadPack, "acme".into(), "api".into())
        );
        for bad in [
            "git-upload-archive '/acme/api.git'",
            "rm -rf /",
            "git-upload-pack '/../etc.git'",
            "git-upload-pack '/acme.git'",
            "git-upload-pack '/acme/a b.git'",
            "git-receive-pack --evil '/acme/api.git'",
            "",
        ] {
            assert!(parse_git_command(bad).is_none(), "{bad:?} should be rejected");
        }
    }

    #[test]
    fn pull_rules() {
        let none = HashMap::new();
        let job = Principal::parse("job:acme/api:42");
        assert!(authorize_pull(&job, &none, "acme", "api"));
        assert!(!authorize_pull(&job, &none, "acme", "web"));
        assert!(authorize_pull(&Principal::Dispatcher, &none, "acme", "web"));
        let user = Principal::parse("d@e.com");
        assert!(authorize_pull(&user, &roles(ProjectRole::Viewer), "acme", "api"));
        assert!(!authorize_pull(&user, &none, "acme", "api"));
    }

    #[test]
    fn push_rules() {
        let none = HashMap::new();
        let job = Principal::parse("job:acme/api:42");
        let ok = |p: &Principal, a, r: &HashMap<_, _>, refname| {
            authorize_ref_push(p, a, r, "acme", "api", refname, "main")
        };
        // Job: own branch only, own project only, rw only.
        assert!(ok(&job, CertAccess::ReadWrite, &none, "refs/heads/job/42"));
        assert!(!ok(&job, CertAccess::ReadWrite, &none, "refs/heads/job/43"));
        assert!(!ok(&job, CertAccess::ReadWrite, &none, "refs/heads/main"));
        assert!(!ok(&job, CertAccess::ReadOnly, &none, "refs/heads/job/42"));
        assert!(!authorize_ref_push(
            &job, CertAccess::ReadWrite, &none, "acme", "web", "refs/heads/job/42", "main"
        ));
        // Dispatcher: protected refs allowed.
        assert!(ok(&Principal::Dispatcher, CertAccess::ReadWrite, &none, "refs/heads/main"));
        assert!(ok(&Principal::Dispatcher, CertAccess::ReadWrite, &none, "refs/tags/v1"));
        // Users: job branches only, Member+ only.
        let user = Principal::parse("d@e.com");
        assert!(ok(&user, CertAccess::ReadWrite, &roles(ProjectRole::Member), "refs/heads/job/7"));
        assert!(!ok(&user, CertAccess::ReadWrite, &roles(ProjectRole::Viewer), "refs/heads/job/7"));
        assert!(!ok(&user, CertAccess::ReadWrite, &roles(ProjectRole::Admin), "refs/heads/main"));
        assert!(!ok(&user, CertAccess::ReadWrite, &roles(ProjectRole::Admin), "refs/heads/job/x"));
        assert!(!ok(&user, CertAccess::ReadWrite, &roles(ProjectRole::Admin), "refs/tags/v1"));
    }

    #[tokio::test]
    async fn job_credential_issuance_and_cert_contents() {
        let dir = tempfile::tempdir().unwrap();
        let ca = dir.path().join("ca");
        run("ssh-keygen", &["-q", "-t", "ed25519", "-N", "", "-f", ca.to_str().unwrap()])
            .await
            .unwrap();

        let ssh_ca = SshCa::new(&ca);
        let cred = ssh_ca
            .issue_job_credential("acme", "api", 42, CertAccess::ReadOnly, chrono::Duration::hours(1))
            .await
            .unwrap();
        assert!(cred.private_key.contains("OPENSSH PRIVATE KEY"));
        assert!(cred.certificate.starts_with("ssh-ed25519-cert-v01@openssh.com"));

        // ssh-keygen -L pretty-prints the cert; assert principal + forced command.
        let cert_path = dir.path().join("cert.pub");
        tokio::fs::write(&cert_path, &cred.certificate).await.unwrap();
        let out = tokio::process::Command::new("ssh-keygen")
            .args(["-L", "-f", cert_path.to_str().unwrap()])
            .output()
            .await
            .unwrap();
        let listing = String::from_utf8_lossy(&out.stdout).into_owned();
        assert!(listing.contains("job:acme/api:42"), "{listing}");
        assert!(listing.contains("--access ro"), "{listing}");
    }

    #[tokio::test]
    async fn user_cert_carries_roles_in_forced_command() {
        let dir = tempfile::tempdir().unwrap();
        let ca = dir.path().join("ca");
        run("ssh-keygen", &["-q", "-t", "ed25519", "-N", "", "-f", ca.to_str().unwrap()])
            .await
            .unwrap();
        let user_key = dir.path().join("id");
        run("ssh-keygen", &["-q", "-t", "ed25519", "-N", "", "-f", user_key.to_str().unwrap()])
            .await
            .unwrap();
        let pubkey = tokio::fs::read_to_string(user_key.with_extension("pub")).await.unwrap();

        let cert = SshCa::new(&ca)
            .sign_user_cert(&pubkey, "d@e.com", &roles(ProjectRole::Member), chrono::Duration::hours(24))
            .await
            .unwrap();
        let cert_path = dir.path().join("cert.pub");
        tokio::fs::write(&cert_path, &cert).await.unwrap();
        let out = tokio::process::Command::new("ssh-keygen")
            .args(["-L", "-f", cert_path.to_str().unwrap()])
            .output()
            .await
            .unwrap();
        let listing = String::from_utf8_lossy(&out.stdout).into_owned();
        assert!(listing.contains("d@e.com"), "{listing}");
        assert!(listing.contains("--kind user"), "{listing}");
    }
}
