//! `chuggernaut schema` — emit the JSON Schema for the repo-authored YAML
//! files (spec §1.1), derived from the same serde types the platform parses
//! with, so the schema can never drift from the code.
//!
//! Intended use in a project repo:
//!
//! ```sh
//! chuggernaut schema job-type > jobs/.job-type.schema.json
//! chuggernaut schema defaults > jobs/.defaults.schema.json
//! ```
//!
//! then point yaml-language-server at it from each file:
//!
//! ```yaml
//! # yaml-language-server: $schema=.job-type.schema.json
//! ```
//!
//! Shape errors surface in the editor as you type; the semantic rules JSON
//! Schema cannot express (§1.1 field-rules matrices, prompt-file existence)
//! remain `chuggernaut validate` / release validation.
//!
//! The third kind describes the **§6.2 HTTP surface** instead of a file:
//!
//! ```sh
//! chuggernaut schema api > schemas/api.schema.json
//! ```
//!
//! It is the machine-readable half of the wire contract the operator UI
//! hand-mirrors today (NORTH-STAR §2): one bundle document whose `$defs` holds
//! a named schema per type the API serializes, generated from the same serde
//! types that serve it. Emission stays on stdout like the other kinds — the CLI
//! also runs inside consumer project repos, where a hardcoded output path would
//! be meaningless.

use clap::{Parser, ValueEnum};

#[derive(Parser)]
pub struct SchemaArgs {
    /// Which contract the schema describes.
    #[arg(value_enum)]
    pub kind: SchemaKind,
}

#[derive(Clone, Copy, ValueEnum)]
pub enum SchemaKind {
    /// jobs/{type}.yaml
    JobType,
    /// jobs/_defaults.yaml
    Defaults,
    /// The §6.2 HTTP surface (schemas/api.schema.json)
    Api,
}

pub fn generate(kind: SchemaKind) -> anyhow::Result<String> {
    let schema = match kind {
        SchemaKind::JobType => schemars::schema_for!(types::JobType),
        SchemaKind::Defaults => schemars::schema_for!(types::ProjectDefaults),
        // Not one root type but the whole wire vocabulary, so this arm builds
        // its document rather than naming a single `schema_for!` root.
        SchemaKind::Api => api_bundle(),
    };
    let mut pretty = serde_json::to_string_pretty(&schema)?;
    pretty.push('\n');
    Ok(pretty)
}

pub fn run(args: SchemaArgs) -> anyhow::Result<()> {
    print!("{}", generate(args.kind)?);
    Ok(())
}

/// Register each listed type as a named `$defs` entry of the api bundle.
///
/// Every covered type is named explicitly, including ones already reachable
/// from another root: the lists below *are* the statement of what the generated
/// contract covers, and re-registering a type is idempotent.
macro_rules! cover {
    ($generator:expr, $($t:ty),+ $(,)?) => {
        $( let _ = $generator.subschema_for::<$t>(); )+
    };
}

/// The §6.2 wire contract as one bundle document: `$defs` carries one named
/// schema per type the HTTP surface serializes, and the document has no root
/// type of its own — a response is one of the `$defs`, not the bundle.
///
/// Deliberately **not** covered, because no Rust type describes them: the reply
/// envelopes the dispatcher assembles with `serde_json::json!` (job criteria,
/// the job-type list/detail wrapper, tree/file, graph, project + platform
/// config, health, task output, artifact and attachment lists) and the
/// `serde_json::Value` request bodies the api forwards verbatim (job create/
/// update/members, project create/link). Naming those in Rust is its own
/// change; until then they stay hand-mirrored in TypeScript.
fn api_bundle() -> schemars::Schema {
    let mut generator = schemars::SchemaGenerator::default();
    api_bundle_job_records(&mut generator);
    api_bundle_platform_records(&mut generator);
    api_bundle_job_config(&mut generator);
    api_bundle_request_bodies(&mut generator);

    let mut root = serde_json::Map::new();
    if let Some(meta_schema) = generator.settings().meta_schema.clone() {
        root.insert("$schema".into(), meta_schema.into_owned().into());
    }
    root.insert("title".into(), "chuggernaut HTTP surface".into());
    root.insert(
        "description".into(),
        "Generated by `chuggernaut schema api` (spec §6.2). Do not edit; \
         `committed_schemas_are_current` fails when this file goes stale."
            .into(),
    );
    // Sorted, so the emitted order is a property of this code rather than of
    // schemars' traversal or a downstream `preserve_order` feature — a drift
    // test that flapped would poison every unrelated job's CI.
    let defs: std::collections::BTreeMap<String, serde_json::Value> =
        generator.take_definitions(true).into_iter().collect();
    root.insert("$defs".into(), defs.into_iter().collect());
    root.into()
}

/// The job and task records the jobs/tasks/queue endpoints serve, plus the
/// channel post the jobs *list* projection carries.
fn api_bundle_job_records(generator: &mut schemars::SchemaGenerator) {
    cover!(
        generator,
        types::Job,
        types::JobSummary<'static>,
        types::JobState,
        types::Escalation,
        types::Task,
        types::TaskPhase,
        types::TaskKind,
        types::TaskState,
        types::Performer,
        types::PendingReason,
        types::ReworkReason,
        types::TaskResult,
        types::TokenUsage,
        types::EscalationAction,
        types::QueueSnapshot,
        types::QueueEntry,
        types::ChannelUpdate,
        types::ChannelOrigin,
    );
}

/// Platform- and project-level records: the fleet and dispatcher snapshots, the
/// deploy report a command work task harvests, the origin link/release state,
/// and the caller's identity.
fn api_bundle_platform_records(generator: &mut schemars::SchemaGenerator) {
    cover!(
        generator,
        types::FleetStatus,
        types::FleetNode,
        types::SlotOccupant,
        types::DispatcherConfigSnapshot,
        types::WorkerNode,
        types::worker::RefreshOutcome,
        types::worker::RefreshResult,
        types::DeployReport,
        types::DeployLeg,
        types::LegStatus,
        types::OriginLink,
        types::ReleaseState,
        types::ReleaseStatus,
        types::Identity,
        types::IdentityKind,
        types::ProjectRole,
    );
}

/// The job-type definition the job-type detail endpoint serves parsed (the same
/// type `schema job-type` describes, here as one `$defs` entry among many).
fn api_bundle_job_config(generator: &mut schemars::SchemaGenerator) {
    cover!(
        generator,
        types::JobType,
        types::WorkSpec,
        types::WorkType,
        types::ReviewSpec,
        types::WrapUpSpec,
        types::WrapUpMode,
        types::Evaluator,
        types::EvaluatorType,
        types::Placement,
        types::job_type::Provider,
        types::job_type::Resources,
    );
}

/// Request bodies: the operator's task resolution (typed in `types`) and the
/// bodies typed in `api` itself.
fn api_bundle_request_bodies(generator: &mut schemars::SchemaGenerator) {
    cover!(
        generator,
        types::TaskResolution,
        api::routes::LoginBody,
        api::routes::SshCertBody,
        api::routes::MemberRoleBody,
        api::routes::FileQuery,
        api::routes::OutputQuery,
    );
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    /// The committed schemas (schemas/) must match what the current types
    /// generate. Regenerate with:
    ///   cargo run -p chuggernaut -- schema job-type > schemas/job-type.schema.json
    ///   cargo run -p chuggernaut -- schema defaults > schemas/defaults.schema.json
    ///   cargo run -p chuggernaut -- schema api > schemas/api.schema.json
    ///
    /// For `api` this is the whole enforcement of the §6.2 contract: a field
    /// added to any covered type changes the generated bundle, so a change that
    /// does not re-emit it fails here rather than silently desynchronizing the
    /// generated TypeScript client from the wire.
    #[test]
    fn committed_schemas_are_current() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../schemas");
        for (kind, file) in [
            (SchemaKind::JobType, "job-type.schema.json"),
            (SchemaKind::Defaults, "defaults.schema.json"),
            (SchemaKind::Api, "api.schema.json"),
        ] {
            let committed = std::fs::read_to_string(root.join(file))
                .unwrap_or_else(|e| panic!("read schemas/{file}: {e} — regenerate (see test doc)"));
            assert_eq!(
                committed,
                generate(kind).unwrap(),
                "schemas/{file} is stale — regenerate (see test doc)"
            );
        }
    }

    /// Emission is deterministic: two runs of the same code produce identical
    /// bytes. The drift test above gates every job's CI, so a bundle whose
    /// `$defs` order varied between runs would fail unrelated work at random.
    #[test]
    fn api_schema_is_deterministic() {
        assert_eq!(
            generate(SchemaKind::Api).unwrap(),
            generate(SchemaKind::Api).unwrap()
        );
    }

    /// Spot-check the api bundle carries the surface it claims: a record type
    /// from each covered family, the list projection that differs from the
    /// stored record, and a request body typed in `api` rather than `types`.
    /// Timestamps must schematize as `date-time` strings, not as an opaque
    /// object — the generated client's `created_at` is a string.
    #[test]
    fn api_schema_covers_the_wire_types() {
        let v: serde_json::Value =
            serde_json::from_str(&generate(SchemaKind::Api).unwrap()).unwrap();
        let defs = v["$defs"].as_object().unwrap();
        for name in [
            "Job",
            "JobSummary",
            "Task",
            "TaskResult",
            "TaskResolution",
            "QueueSnapshot",
            "FleetStatus",
            "DeployReport",
            "Identity",
            "JobType",
            "LoginBody",
        ] {
            assert!(defs.contains_key(name), "$defs is missing {name}");
        }
        // The list projection drops the two heavy prose fields (spec §6.1); the
        // single-job record keeps them. A schema that showed them on both would
        // hand the UI a type that lies about the payload.
        assert!(defs["Job"]["properties"].get("description").is_some());
        assert!(
            defs["JobSummary"]["properties"]
                .get("description")
                .is_none()
        );
        assert_eq!(
            defs["Job"]["properties"]["created_at"]["format"],
            serde_json::json!("date-time")
        );
    }

    /// Spot-check the schema actually encodes the contract: the top level is
    /// tolerant of unknown fields (schema-evolution laxity, spec §14) while the
    /// gate-relevant `Evaluator` block stays strict; finalize enumerates
    /// merge|none.
    #[test]
    fn job_type_schema_shape() {
        let v: serde_json::Value =
            serde_json::from_str(&generate(SchemaKind::JobType).unwrap()).unwrap();
        // Top level tolerates unknown fields (no `additionalProperties: false`)
        // so a config that runs ahead of the dispatcher is a warning, not a
        // hard editor error.
        assert_ne!(v["additionalProperties"], serde_json::json!(false));
        // The Evaluator block, by contrast, stays strict: an unknown key there
        // could silently skip a gate.
        assert_eq!(
            v["$defs"]["Evaluator"]["additionalProperties"],
            serde_json::json!(false)
        );
        let finalize = &v["$defs"]["WrapUpMode"];
        let variants: Vec<&str> = finalize["oneOf"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|o| o["const"].as_str())
            .collect();
        assert_eq!(variants, ["merge", "none"], "{finalize}");
    }
}
