use async_nats::jetstream;
use bytes::Bytes;

/// A thin wrapper around the NATS client and JetStream context that
/// automatically applies a subject prefix. In production the prefix is
/// empty (passthrough). In tests each instance gets a UUID prefix so
/// every test has its own namespace inside a shared NATS server.
#[derive(Clone)]
pub struct NatsClient {
    client: async_nats::Client,
    js: jetstream::Context,
    prefix: Option<String>,
}

impl NatsClient {
    pub fn new(client: async_nats::Client, js: jetstream::Context) -> Self {
        Self {
            client,
            js,
            prefix: None,
        }
    }

    pub fn with_prefix(
        client: async_nats::Client,
        js: jetstream::Context,
        prefix: String,
    ) -> Self {
        Self {
            client,
            js,
            prefix: Some(prefix),
        }
    }

    /// The raw prefix (or None). Exposed for nats_init to name buckets/streams.
    pub fn prefix(&self) -> Option<&str> {
        self.prefix.as_deref()
    }

    /// Apply the prefix to a subject.
    fn prefixed(&self, subject: &str) -> String {
        match &self.prefix {
            Some(p) => format!("{p}_{subject}"),
            None => subject.to_string(),
        }
    }

    /// Strip the prefix from an incoming subject to recover the base subject.
    pub fn strip_prefix<'a>(&self, subject: &'a str) -> &'a str {
        match &self.prefix {
            Some(p) => {
                let pat = format!("{p}_");
                subject.strip_prefix(&pat).unwrap_or(subject)
            }
            None => subject,
        }
    }

    // -----------------------------------------------------------------------
    // Delegated methods — these are the only NATS operations the dispatcher
    // uses, so we only wrap what we need.
    // -----------------------------------------------------------------------

    pub async fn publish(
        &self,
        subject: &str,
        payload: Bytes,
    ) -> Result<(), async_nats::PublishError> {
        let s = self.prefixed(subject);
        self.client.publish(s, payload).await
    }

    pub async fn subscribe(
        &self,
        subject: &str,
    ) -> Result<async_nats::Subscriber, async_nats::SubscribeError> {
        let s = self.prefixed(subject);
        self.client.subscribe(s).await
    }

    pub async fn request(
        &self,
        subject: &str,
        payload: Bytes,
    ) -> Result<async_nats::Message, async_nats::RequestError> {
        let s = self.prefixed(subject);
        self.client.request(s, payload).await
    }

    /// Publish to a JetStream subject (for streams like TRANSITIONS).
    pub async fn js_publish(
        &self,
        subject: &str,
        payload: Bytes,
    ) -> Result<async_nats::jetstream::context::PublishAckFuture, async_nats::jetstream::context::PublishError>
    {
        let s = self.prefixed(subject);
        self.js.publish(s, payload).await
    }

    /// Publish to a raw (non-prefixed) subject. Used for NATS reply subjects
    /// which are generated by NATS itself and must not be prefixed.
    pub async fn publish_raw(
        &self,
        subject: String,
        payload: Bytes,
    ) -> Result<(), async_nats::PublishError> {
        self.client.publish(subject, payload).await
    }

    /// Access the underlying JetStream context (for KV operations, etc.)
    pub fn jetstream(&self) -> &jetstream::Context {
        &self.js
    }
}
